import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const kenyan_coffee = localFont({
  src: [
    {
      path: "../public/fonts/kenyan coffee bd.otf",
      weight: "700",
    },
    {
      path: "../public/fonts/kenyan coffee rg.otf",
      weight: "400",
    },
  ],
  variable: "--font-kenyan-coffee",
});

const serenata_vantages = localFont({
  src: [
    {
      path: "../public/fonts/Serenata Vantages Bold.ttf",
      weight: "700",
    },
    {
      path: "../public/fonts/Serenata Vantages Regular.ttf",
      weight: "400",
    },
  ],
  variable: "--font-serenata-vantages",
});

export const metadata: Metadata = {
  title: "Verdroof",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${serenata_vantages.variable} ${kenyan_coffee.variable} font-sans`}
    >
      <body>{children}</body>
    </html>
  );
}
